# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/nvme0n1p1";
    label = "boot_partition";
    noCheck = true;
    options = [
      "x-initrd.mount"
    ];
  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/85c27cda-9030-438e-84ad-2bf8cfaec68e";
    fsType = "ext4";
    label = "nixos_root";
    options = [
      "defaults"
    ];
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/397620dc-c136-4740-9ffc-8037fa85060a";
    fsType = "ext4";
    label = "home_partition";
    options = [
      "defaults"
    ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c0c79a8-ee8e-436d-8ff2-62625052a631"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
